### ISSUE TITLE
Problems with docker-compose.yml

### ISSUE THREAD

**Issue by AlexTheKing** [Alexundar/NewsAgregator#9]
Нет необходимости подключать том /app - все данные сохраняются в монгу.
Я поправил способ запуска приложения, поэтому env vars тоже не нужны

```
web:
  build: .
  ports:
    - "5000:5000"
  links:
    - db
db:
  image: mongo
```
